package:
  name: iminuit
  version: "1.2"

source:
  fn: iminuit-1.2.tar.gz
  url: https://pypi.python.org/packages/c9/fd/87931ec898e16557b8f6ae6e576743d00ca085c1cb4eb4673d8f4b02ac20/iminuit-1.2.tar.gz
  md5: 4701ec472cae42015e26251703e6e984

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - iminuit
    - iminuit.frontends
    - iminuit.tests

about:
  home: https://github.com/iminuit/iminuit
  license: GNU General Public License (GPL) or MIT License
  summary: 'Interactive _Minimization Tools based on MINUIT'
  license_family: LGPL
