package:
  name: algopy
  version: "0.5.3"

source:
  fn: algopy-0.5.3.tar.gz
  url: https://pypi.python.org/packages/74/c4/60158e608438e948d9ca7554549e8a4978586dbfb4d81ff78cadc590da1f/algopy-0.5.3.tar.gz
  md5: bc2c83b5cb7635fb5b4b309d0312c1bd
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - algopy = algopy:main
    #
    # Would create an entry point called algopy that calls algopy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy
    - scipy

  run:
    - python
    - numpy
    - scipy

test:
  # Python imports
  imports:
    - numpy
    - scipy
    - algopy
    - algopy.fft
    - algopy.linalg
    - algopy.nthderiv
    - algopy.special
    - algopy.tests
    - algopy.tracer
    - algopy.tracer.tests
    - algopy.tracer.tests.test_output
    - algopy.utpm
    - algopy.utpm.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://packages.python.org/algopy
  license: BSD
  summary: 'ALGOPY: Taylor Arithmetic Computation and Algorithmic Differentiation'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
