package:
  name: multinest
  version: "3.10"

source:
  git_url: https://github.com/JohannesBuchner/MultiNest

requirements:
  build:
    - cmake
    - mpi4py
    - lapack

  run:
    - mpi4py
    - lapack

about:
  home: https://github.com/JohannesBuchner/MultiNest

